bitcoind:
  type: union
  name: Bitcoin Core
  description: The Bitcoin Core node to connect to
  tag:
    id: type
    name: Type
    description: |
      - Internal: The Bitcoin Core service installed to your Embassy
      - External: A Bitcoin Core node running on a different device
      - Quick Connect: A Quick Connect URL for an unpruned Bitcoin Core node
    variantNames:
      internal: Internal
      external: External
      quick-connect: Quick Connect
  default: internal
  variants:
    internal:
      address:
        type: pointer
        name: Local Address
        description: The LAN IP address of your Bitcoin Core service
        subtype: app
        app-id: bitcoind
        target: lan-address
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user for Bitcoin Core
        subtype: app
        app-id: bitcoind
        target: config
        index: "rpc.username"
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user for Bitcoin Core
        subtype: app
        app-id: bitcoind
        target: config
        index: "rpc.password"
    external:
      address:
        type: string
        name: Public Address
        description: The public address of your Bitcoin Core RPC server
        nullable: false
      user:
        type: string
        name: RPC Username
        description: The username for the RPC user on your Bitcoin Core RPC server
        nullable: false
      password:
        type: string
        name: RPC Password
        description: The password for the RPC user on your Bitcoin Core RPC server
        nullable: false
    quick-connect:
      quick-connect-url:
        type: string
        name: Quick Connect URL
        description: The Quick Connect URL for your Bitcoin Core RPC server
        nullable: false
        pattern: 'btcstandup://[^:]*:[^@]*@[a-zA-Z0-9.-]+:[0-9]+(/(\?(label=.+)?)?)?'
        patternDescription: Must be a valid Quick Connect URL. For help, check out https://github.com/BlockchainCommons/Gordian/blob/master/Docs/Quick-Connect-API.md
users:
  type: list
  name: RPC Users
  description: Credentials and permissions for each RPC User
  range: "[0,*)"
  subtype: object
  spec:
    uniqueBy: name
    displayAs: "{{name}}"
    spec:
      name:
        type: string
        name: Username
        description: The username for the RPC User
        nullable: false
        default: bitcoin
      password:
        type: string
        name: Password
        description: The password for the RPC User
        nullable: false
        default:
          charset: "a-z,A-Z,0-9"
          len: 22
      allowed-calls:
        type: list
        name: Allowed Calls
        description: The list of all RPC methods this user is allowed to make
        subtype: enum
        range: "[0, *)"
        spec:
          type: enum
          values:
            - getbestblockhash
            - getblock
            - getinfo
            - getblockchaininfo
            - getblockcount
            - getblockhash
            - getblockheader
            - getblockstats
            - getchaintips
            - getchaintxstats
            - getdifficulty
            - getmempoolancestors
            - getmempooldescendants
            - getmempoolentry
            - getmempoolinfo
            - getrawmempool
            - gettxout
            - gettxoutproof
            - gettxoutsetinfo
            - preciousblock
            - pruneblockchain
            - savemempool
            - scantxoutset
            - verifychain
            - verifytxoutproof
            - getmemoryinfo
            - getrpcinfo
            - help
            - logging
            - stop
            - uptime
            - generate
            - generatetoaddress
            - getblocktemplate
            - getmininginfo
            - getnetworkhashps
            - prioritisetransaction
            - submitblock
            - submitheader
            - addnode
            - clearbanned
            - disconnectnode
            - getaddednodeinfo
            - getconnectioncount
            - getnettotals
            - getnetworkinfo
            - getnodeaddresses
            - getpeerinfo
            - listbanned
            - ping
            - setban
            - setnetworkactive
            - analyzepsbt
            - combinepsbt
            - combinerawtransaction
            - converttopsbt
            - createpsbt
            - createrawtransaction
            - decodepsbt
            - decoderawtransaction
            - decodescript
            - finalizepsbt
            - fundrawtransaction
            - getrawtransaction
            - joinpsbts
            - sendrawtransaction
            - signrawtransactionwithkey
            - testmempoolaccept
            - utxoupdatepsbt
            - createmultisig
            - deriveaddresses
            - estimatesmartfee
            - getdescriptorinfo
            - signmessagewithprivkey
            - validateaddress
            - verifymessage
            - abandontransaction
            - abortrescan
            - addmultisigaddress
            - backupwallet
            - bumpfee
            - createwallet
            - dumpprivkey
            - dumpwallet
            - encryptwallet
            - getaddressesbylabel
            - getaddressinfo
            - getbalance
            - getnewaddress
            - getrawchangeaddress
            - getreceivedbyaddress
            - getreceivedbylabel
            - gettransaction
            - getunconfirmedbalance
            - getwalletinfo
            - importaddress
            - importmulti
            - importprivkey
            - importprunedfunds
            - importpubkey
            - importwallet
            - keypoolrefill
            - listaddressgroupings
            - listlabels
            - listlockunspent
            - listreceivedbyaddress
            - listreceivedbylabel
            - listsinceblock
            - listtransactions
            - listunspent
            - listwalletdir
            - listwallets
            - loadwallet
            - lockunspent
            - removeprunedfunds
            - rescanblockchain
            - sendmany
            - sendtoaddress
            - sethdseed
            - setlabel
            - settxfee
            - signmessage
            - signrawtransactionwithwallet
            - unloadwallet
            - walletcreatefundedpsbt
            - walletlock
            - walletpassphrase
            - walletpassphrasechange
            - walletprocesspsbt
        default:
          - getbestblockhash
          - getblock
          - getinfo
          - getblockchaininfo
          - getblockcount
          - getblockhash
          - getblockheader
          - getblockstats
          - getchaintips
          - getchaintxstats
          - getdifficulty
          - getmempoolancestors
          - getmempooldescendants
          - getmempoolentry
          - getmempoolinfo
          - getrawmempool
          - gettxout
          - gettxoutproof
          - gettxoutsetinfo
          - preciousblock
          - pruneblockchain
          - savemempool
          - scantxoutset
          - verifychain
          - verifytxoutproof
          - getmemoryinfo
          - getrpcinfo
          - help
          - logging
          - stop
          - uptime
          - generate
          - generatetoaddress
          - getblocktemplate
          - getmininginfo
          - getnetworkhashps
          - prioritisetransaction
          - submitblock
          - submitheader
          - addnode
          - clearbanned
          - disconnectnode
          - getaddednodeinfo
          - getconnectioncount
          - getnettotals
          - getnetworkinfo
          - getnodeaddresses
          - getpeerinfo
          - listbanned
          - ping
          - setban
          - setnetworkactive
          - analyzepsbt
          - combinepsbt
          - combinerawtransaction
          - converttopsbt
          - createpsbt
          - createrawtransaction
          - decodepsbt
          - decoderawtransaction
          - decodescript
          - finalizepsbt
          - fundrawtransaction
          - getrawtransaction
          - joinpsbts
          - sendrawtransaction
          - signrawtransactionwithkey
          - testmempoolaccept
          - utxoupdatepsbt
          - createmultisig
          - deriveaddresses
          - estimatesmartfee
          - getdescriptorinfo
          - signmessagewithprivkey
          - validateaddress
          - verifymessage
          - abandontransaction
          - abortrescan
          - addmultisigaddress
          - backupwallet
          - bumpfee
          - createwallet
          - dumpprivkey
          - dumpwallet
          - encryptwallet
          - getaddressesbylabel
          - getaddressinfo
          - getbalance
          - getnewaddress
          - getrawchangeaddress
          - getreceivedbyaddress
          - getreceivedbylabel
          - gettransaction
          - getunconfirmedbalance
          - getwalletinfo
          - importaddress
          - importmulti
          - importprivkey
          - importprunedfunds
          - importpubkey
          - importwallet
          - keypoolrefill
          - listaddressgroupings
          - listlabels
          - listlockunspent
          - listreceivedbyaddress
          - listreceivedbylabel
          - listsinceblock
          - listtransactions
          - listunspent
          - listwalletdir
          - listwallets
          - loadwallet
          - lockunspent
          - removeprunedfunds
          - rescanblockchain
          - sendmany
          - sendtoaddress
          - sethdseed
          - setlabel
          - settxfee
          - signmessage
          - signrawtransactionwithwallet
          - unloadwallet
          - walletcreatefundedpsbt
          - walletlock
          - walletpassphrase
          - walletpassphrasechange
          - walletprocesspsbt
      fetch-blocks:
        type: boolean
        name: Fetch Blocks
        description: Fetch blocks from the network if pruned from disk
        default: true
  default: []
advanced:
  type: object
  name: Advanced
  description: Advanced settings for Bitcoin Proxy
  nullable: false
  spec:
    tor-only:
      type: boolean
      name: Only Tor Peers
      description: Use Tor for all peer connections
      default: false
    peer-timeout:
      type: number
      name: Peer Message Timeout
      description: How long to wait for a response from a peer before failing
      nullable: false
      integral: true
      units: Seconds
      range: "[0, *)"
      default: 30
    max-peer-age:
      type: number
      name: Maximum Peer Age
      description: How long to wait before refreshing the peer list
      nullable: false
      integral: true
      units: Seconds
      range: "[0, *)"
      default: 300
